-- ADE 20-min demo seed
-- Contract: ADE_DEMO.OPS with ORDERS (ORDER_ID, ORDER_TOTAL, ORDER_TS),
-- broken task LOAD_DAILY_ORDERS that still selects AMOUNT, executed once to fail,
-- plus ORDERS_SUMMARY view (downstream consumer) for dependency assessment demos.

CREATE DATABASE IF NOT EXISTS ADE_DEMO;
CREATE SCHEMA IF NOT EXISTS ADE_DEMO.OPS;

USE DATABASE ADE_DEMO;
USE SCHEMA OPS;

CREATE OR REPLACE TABLE ADE_DEMO.OPS.ORDERS (
  ORDER_ID     NUMBER,
  ORDER_TOTAL  NUMBER(12, 2),
  ORDER_TS     TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE ADE_DEMO.OPS.ORDERS_DAILY (
  ORDER_ID     NUMBER,
  ORDER_TOTAL  NUMBER(12, 2),
  ORDER_TS     TIMESTAMP_NTZ
);

-- 30 sample rows (deterministic)
INSERT INTO ADE_DEMO.OPS.ORDERS (ORDER_ID, ORDER_TOTAL, ORDER_TS)
SELECT
  SEQ4() + 1,
  UNIFORM(10, 500, RANDOM())::NUMBER(12, 2),
  DATEADD('hour', -UNIFORM(1, 48, RANDOM()), CURRENT_TIMESTAMP()::TIMESTAMP_NTZ)
FROM TABLE(GENERATOR(ROWCOUNT => 30));

-- Downstream consumer for object dependency assessment (blast radius > 1)
CREATE OR REPLACE VIEW ADE_DEMO.OPS.ORDERS_SUMMARY AS
SELECT
  COUNT(*) AS ORDER_COUNT,
  SUM(ORDER_TOTAL) AS TOTAL_ORDER_TOTAL,
  MAX(ORDER_TS) AS LATEST_ORDER_TS
FROM ADE_DEMO.OPS.ORDERS;

-- Intentional bug: body still references AMOUNT (renamed to ORDER_TOTAL on ORDERS)
-- Adjust WAREHOUSE if COMPUTE_WH is not available in your account.
CREATE OR REPLACE TASK ADE_DEMO.OPS.LOAD_DAILY_ORDERS
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
AS
  INSERT INTO ADE_DEMO.OPS.ORDERS_DAILY
  SELECT ORDER_ID, AMOUNT, ORDER_TS
  FROM ADE_DEMO.OPS.ORDERS
  WHERE ORDER_TS >= DATEADD('day', -1, CURRENT_TIMESTAMP());

-- Run once so TASK_HISTORY has a fresh failed execution (compile/runtime SQL error)
EXECUTE TASK ADE_DEMO.OPS.LOAD_DAILY_ORDERS;

-- Optional: confirm failure (run manually in Snowsight)
-- SELECT *
-- FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
--   SCHEDULED_TIME_RANGE_START => DATEADD('hour', -1, CURRENT_TIMESTAMP()),
--   TASK_NAME => 'LOAD_DAILY_ORDERS'
-- ))
-- ORDER BY SCHEDULED_TIME DESC
-- LIMIT 5;
